services:
  app:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_HELP_URL=${REACT_APP_HELP_URL:-https://docs.nobl9.com}
    command: nginx -g 'daemon off;'

  dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_HELP_URL=${REACT_APP_HELP_URL:-https://docs.nobl9.com}
    command: sh -c "npm install && npm start -- --host 0.0.0.0"

  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.go-backend
    environment:
      - NOBL9_SDK_CLIENT_ID=your-client-id
      - NOBL9_SDK_CLIENT_SECRET=your-client-secret
    ports:
      - "4000:4000" 